# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    bcard.tblprefix_subscriber:
        class: BcardBundle\Subscriber\TablePrefixSubscriber
        arguments: [%bcard.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    mailingbundle.twig_extension:
        class: BcardBundle\Twig\AppExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }