bcard_homepage:
    path:     /
    defaults: { _controller: BcardBundle:Default:index }
models:
    path: /models/{id}
    defaults: { _controller: BcardBundle:Model:index }
upload_logo:
    path: /uploadlogo
    defaults: { _controller: BcardBundle:Model:uploadlogo }

bcard_generate_form :
    path: /generateform
    defaults: { _controller : BcardBundle:Model:generateForm}
upload_file :
    path: /uploadfile
    defaults: { _controller : BcardBundle:Model:uploadfile}
submitinvoice :
    path: /submitinvoice
    defaults: { _controller : BcardBundle:Model:submitInvoice}
generatepdf :
    path: /admin/generatePdf/{id}
    defaults: { _controller : BcardBundle:Admin:generatePdf}