services:
#    bcard.example:
#        class: BcardBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.template:
        class: BcardBundle\Admin\TemplateAdmin
        arguments: [~, BcardBundle\Entity\Template, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template" ,label: 'Template', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            - [ setTemplate, [edit, BcardBundle:Template:edit.html.twig]]
    admin.Invoice:
        class: BcardBundle\Admin\InvoiceAdmin
        arguments: [~, BcardBundle\Entity\Invoice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template" ,label: 'Commande', icon:'<i class="fa fa-envelope"></i>' }

    admin.fonts:
        class: BcardBundle\Admin\FontsAdmin
        arguments: [~, BcardBundle\Entity\Fonts, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template" ,label: 'List des fonts google', icon:'<i class="fa fa-envelope"></i>' }
