<?php

namespace BcardBundle\Repository;

/**
 * FontsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FontsRepository extends \Doctrine\ORM\EntityRepository
{
}
